# Generated by Django 4.2.6 on 2023-10-06 09:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('scope', models.CharField(max_length=255, verbose_name='Scope')),
                ('phone', models.CharField(max_length=31, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('is_admin', models.BooleanField(default=False, verbose_name='IsAdmin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companymembers', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company member',
                'verbose_name_plural': 'Company members',
            },
        ),
    ]
